print("Law 1-any number as base and exponent of that base is 0 then answer will be 1"
)
print("2^0 is:  ",pow(2,0)
)

print("Law 2-any number as base and exponent of that base is 1 the answer is base itself")
print("5^1 the result is:  ",pow(5,1),", and  12^1 is: ",pow(12,1))

print("law 3 - any number as base and exponent of that base is -1 then  answer will be reciprocal of that base")
print("7 ^ -1 = 1/7 is: ", pow(7,-1) )
print("Law 4 - multiply two numbers with same base and different exponents ")
print("x^a* x^b = x^(a+b)" )
print("2^3 * 2^7 = ",pow(2,3)+pow(2,7))
print("Law 5 - divide two numbers with same base and different exponents is ")
print("x^a / x^b  = x^(a – b)" )
print("2^3 / 2^2 = ",pow(2,3)-pow(2,2))
print("Law 6 - (x2)^3 =  (x * x)^3")
print("2^3^4 = 2^(3*4) :  ",pow(2,3)*(pow(2,4)))
print("Law 7 - two numbers to multiply with different base but same exponent then")
print("(x * y)^a = x^a*y^a, (5*4)^2=5^2*4^2 as: ",pow(5,2)*pow(4,2))
print("Law 8 - divide two numbers with different base but same exponent is as")
print("(2 / 3)^4 = 2^4 / 3^4 : ",pow(2,4)/pow(3,4))
print("Law 9 - any number as base and exponent of that base is -1")
print("8^(-2) = 1 / 8(-2) :  ", 1/pow(8,-2))